In [1]:
import numpy as np

In [2]:
x=np.array([1,2,3])

In [3]:
x

array([1, 2, 3])

In [5]:
type(x)

numpy.ndarray

In [6]:
y = np.array([[6, 9, 5], 
              [10, 82, 34]]) 

y

array([[ 6,  9,  5],
       [10, 82, 34]])

In [7]:
y.dim

AttributeError: 'numpy.ndarray' object has no attribute 'dim'

In [8]:
    y.ndim
    

2

In [9]:
y.shape

(2, 3)

In [10]:
y.size

6

In [11]:
y.dtype

dtype('int32')

In [12]:
y.itemsize

4

In [14]:
y.nbytes

24

In [15]:
y = np.array([[6, 9, 5],
              [10, 82, 34]], 
             dtype='float64') 
y
type(y)

numpy.ndarray

In [16]:
y

array([[ 6.,  9.,  5.],
       [10., 82., 34.]])

In [17]:
n =np.array([5, 10, 15, 20, 25])

In [18]:
n


array([ 5, 10, 15, 20, 25])

In [19]:
type(n)

numpy.ndarray

In [20]:
n.ndim

1

In [21]:
n.shape

(5,)

In [22]:
n.size

5

In [23]:
n=np.array([[-1, -2, -3, -4], [-2,-4, -6, -8]])


In [24]:
n

array([[-1, -2, -3, -4],
       [-2, -4, -6, -8]])

In [25]:
n.ndim

2

In [26]:
n.shape

(2, 4)

In [27]:
n.size

8

In [28]:
type(n)

numpy.ndarray

In [30]:
n.nbytes

32

In [31]:
import numpy as np
a = [[[4.1, 2.5], [1.1, 2.3], [9.1, 2.5]], 
     [[8.6, 9.9],[3.6, 4.3], [6.6, 0.3]]]


In [37]:
x=np.array(a,dtype='float64')

In [38]:
x

array([[[4.1, 2.5],
        [1.1, 2.3],
        [9.1, 2.5]],

       [[8.6, 9.9],
        [3.6, 4.3],
        [6.6, 0.3]]])

In [39]:
type(x)

numpy.ndarray

In [40]:
x.ndim

3

In [41]:
x.size

12

In [42]:
x.shape

(2, 3, 2)

In [45]:
x=np.zeros(shape=(2,3))

x

array([[0., 0., 0.],
       [0., 0., 0.]])

In [46]:
x=np.full(shape=(2,4),fill_value=10.2)

x

array([[10.2, 10.2, 10.2, 10.2],
       [10.2, 10.2, 10.2, 10.2]])

In [52]:
x=np.arange(3,15,2.5,dtype='int')

x

array([ 3,  5,  7,  9, 11])

In [49]:
x=np.linspace(3,15,5)

x

array([ 3.,  6.,  9., 12., 15.])

In [56]:
#creating ndarrays using random values


In [57]:
np.random.seed(100)
x=np.random.rand(2)
x

array([0.54340494, 0.27836939])

In [58]:
np.random.randint(10,20,35)

array([17, 10, 14, 12, 15, 12, 12, 12, 11, 10, 18, 14, 10, 19, 16, 12, 14,
       11, 15, 13, 14, 14, 13, 17, 11, 11, 17, 17, 10, 12, 19, 19, 13, 12,
       15])

In [59]:
## Standard normal distribution


In [60]:
np.random.seed(10)
x=np.random.randn(3)
x

array([ 1.3315865 ,  0.71527897, -1.54540029])

In [62]:
x=10+2*np.random.randn(5) # normal distribution with mean 10 and sd 2
x

array([10.00858286,  9.65079958, 10.86605238, 12.40607475,  8.06986866])

In [63]:
#Reading Data from a file
#loadtxt is used to read data from a text file or any input data stream.

In [72]:
from io import StringIO

In [73]:
from io import StringIO

In [74]:
import numpy as np

In [77]:
x=StringIO('''1 2 3 4''')

x

In [78]:
d=np.loadtxt(x,delimiter=' ')
d

array([1., 2., 3., 4.])

In [79]:
import numpy as np

z = np.eye(2)
print(z)

[[1. 0.]
 [0. 1.]]


In [82]:
x=[[[-1,1],[-2,2]],[[-3,3],[-4,4]]]

x

[[[-1, 1], [-2, 2]], [[-3, 3], [-4, 4]]]

In [83]:
y=np.array(x)

In [84]:
y

array([[[-1,  1],
        [-2,  2]],

       [[-3,  3],
        [-4,  4]]])

In [85]:
x=np.ones(shape=(3,2,2))

x

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [87]:
x=np.eye(4)

x

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [93]:
x=np.random.randint(0,2,size=(3,4,2)) #Define a random 3-D array x4 of shape (3, 4, 2) and of numbers between 0 and 1.

In [94]:
x

array([[[1, 0],
        [1, 1],
        [1, 1],
        [1, 0]],

       [[1, 0],
        [0, 0],
        [0, 1],
        [0, 1]],

       [[1, 1],
        [0, 1],
        [0, 1],
        [1, 0]]])

In [95]:
x=5+2.5*np.random.randn(20)#Simulate a random normal distribution of 20 elements, whose mean is 5 and standard deviation 2.5 . Capture the result in x5.

x

array([7.57068519, 5.24787304, 8.49499094, 4.32188003, 6.53301046,
       4.33170703, 3.62672746, 5.33177074, 3.80964496, 8.2711827 ,
       5.4875332 , 6.00052497, 4.15591916, 8.14118066, 3.17007624,
       6.65057888, 4.12282027, 2.6514166 , 3.77665696, 2.98852214])

In [97]:
x=np.arange(0,40,2)  #Define a ndarray x6, having first 20 even numbers.

x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38])

In [98]:
x.size

20

In [99]:
x=np.linspace(10,20,30)  #Define a ndarray x7, having equally spaced 30 numbers between 10 and 20.

x

array([10.        , 10.34482759, 10.68965517, 11.03448276, 11.37931034,
       11.72413793, 12.06896552, 12.4137931 , 12.75862069, 13.10344828,
       13.44827586, 13.79310345, 14.13793103, 14.48275862, 14.82758621,
       15.17241379, 15.51724138, 15.86206897, 16.20689655, 16.55172414,
       16.89655172, 17.24137931, 17.5862069 , 17.93103448, 18.27586207,
       18.62068966, 18.96551724, 19.31034483, 19.65517241, 20.        ])

In [100]:
import numpy as np
np.random.seed(100)
x = np.random.randint(10, 100, 8)

x

array([18, 34, 77, 97, 89, 58, 20, 62])

In [104]:
print(x ,end='\n\n')


[18 34 77 97 89 58 20 62]



In [105]:
y = x.reshape(2,4)


In [106]:
y

array([[18, 34, 77, 97],
       [89, 58, 20, 62]])

In [107]:
print(y, end='\n\n')


[[18 34 77 97]
 [89 58 20 62]]



In [109]:
z=x.reshape(2,2,2)

In [110]:
z

array([[[18, 34],
        [77, 97]],

       [[89, 58],
        [20, 62]]])

In [111]:
print(z,end='\n\n')

[[[18 34]
  [77 97]]

 [[89 58]
  [20 62]]]



In [139]:
import numpy as np
x = np.array([[-1, 1], [-3, 3]])
y = np.array([[-2, 2], [-4, 4]])
print(x,end='\n\n')
print(y)

    

[[-1  1]
 [-3  3]]

[[-2  2]
 [-4  4]]


In [119]:
y

array([[-2,  2],
       [-4,  4]])

In [121]:
np.vstack((x,y))

array([[-1,  1],
       [-3,  3],
       [-2,  2],
       [-4,  4]])

In [122]:
np.hstack((x,y))

array([[-1,  1, -2,  2],
       [-3,  3, -4,  4]])

In [123]:
x=np.arange(30)

x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [126]:
x.reshape(6,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [132]:
res=np.arange(30).reshape((6,5))

In [135]:
x=np.vsplit(res,2)

In [136]:
x

[array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]])]

In [137]:
print(x[0])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [138]:
x=np.vsplit(res,(2,3))

print(x[0],end='\n\n')
print(x[1])

[[0 1 2 3 4]
 [5 6 7 8 9]]

[[10 11 12 13 14]]


In [140]:
y = np.arange(4, 8).reshape(2,2)

In [141]:
y

array([[4, 5],
       [6, 7]])

In [142]:
y = np.arange(4).reshape(2,2)

In [143]:
y

array([[0, 1],
       [2, 3]])

In [144]:
import numpy as np

x = np.arange(4).reshape(2,2)
y = np.arange(4, 8).reshape(2,2)

print(np.hstack((x,y)))

[[0 1 4 5]
 [2 3 6 7]]


In [145]:
import numpy as np

x = np.arange(4).reshape(2,2)

y = np.vsplit(x,2)
print(y[0])

[[0 1]]


In [146]:
x=np.arange(20)

x.shape

(20,)

In [147]:
y=x.reshape(2,10)

y.shape

(2, 10)

In [150]:
p=np.hsplit(y,2)

p

[array([[ 0,  1,  2,  3,  4],
        [10, 11, 12, 13, 14]]),
 array([[ 5,  6,  7,  8,  9],
        [15, 16, 17, 18, 19]])]

In [151]:
p[0].shape

(2, 5)

In [152]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [153]:
z=x.reshape(4,5)

z.shape

(4, 5)

In [154]:
res=np.vsplit(z,2)

In [155]:
res[0].shape

(2, 5)

In [156]:
res[0]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [159]:
p=np.array([3, 6, 9, 12])
q=np.array([15, 18, 21, 24, 27, 30])

res=np.hstack((p,q))

In [160]:
res

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [161]:
p=np.array([3, 6, 9, 12])


In [163]:
z=np.square(p)

z

array([  9,  36,  81, 144], dtype=int32)

In [164]:
print(np.sin(p))

[ 0.14112001 -0.2794155   0.41211849 -0.53657292]


In [171]:
print(p.sum(axis=0),end='\n')

30


In [174]:
import numpy as np

x = np.arange(30).reshape(5,6)
x

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [182]:
print(x.argmin(axis=1))

[0 0 0 0 0]


In [183]:
import numpy as np

x = np.arange(4)
print(x**2)

[0 1 4 9]


In [184]:
import numpy as np

print(np.repeat(3, 4))

[3 3 3 3]


In [186]:
x=10+2*np.random.randn(50)



In [187]:
x

array([13.05590604, 11.29441158,  8.64532678,  9.46996241, 11.49221287,
        3.73843034, 10.11924357,  8.24957778, 12.12975666,  8.85369469,
        8.39344303, 12.18594325, 11.30255516, 14.32104958,  8.72173986,
        9.33262494,  9.12479628,  6.18841024,  7.54196134, 11.58979772,
        7.67898372, 11.09211104, 12.32651667, 11.31775404, 11.04737852,
       12.65431215, 12.22504894,  7.85074079, 10.68683233, 11.97087508,
       11.47300336,  5.83907473,  9.40282806,  6.54157815, 10.00701989,
       13.8691906 , 10.43511926, 13.6221637 ,  4.90121173,  9.58876546,
       10.01872725,  5.55835002,  8.26900219,  9.76829411, 10.22882128,
        9.88316505, 11.24437442,  6.72284523, 10.6057547 , 14.15375398])

In [188]:
print(np.mean(x))

9.934688810677002


In [189]:
print(np.std(x))

2.415564467449542


In [190]:
print(np.var(x))

5.834951696404789


In [191]:
x = np.array([[-1, 1], [-2, 2]])

print(x)

[[-1  1]
 [-2  2]]


In [192]:
print(x,end='\n')

[[-1  1]
 [-2  2]]


In [193]:
#nditer method of numpy creates an iterator, which enable accessing each element one after the other.

In [194]:
x

array([[-1,  1],
       [-2,  2]])

In [197]:
for a in np.nditer(x):
  print(a)

-1
1
-2
2


In [198]:
import numpy as np
x = np.arange(10).reshape(2,5)
condition = x % 2 == 0
print(condition)
print(x[condition])

[[ True False  True False  True]
 [False  True False  True False]]
[0 2 4 6 8]


In [199]:
import numpy as np

x = np.arange(30).reshape(3,5,2)

x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]]])

In [200]:
print(x[1,::2,1])

[11 15 19]


In [202]:
import numpy as np

x = np.arange(12).reshape(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [203]:
print(x[-2])

[4 5 6 7]


In [204]:
print(x[-1])

[ 8  9 10 11]


In [205]:
print(x[-3])

[0 1 2 3]


In [206]:
import numpy as np

x = np.array([[1, 2], [3, 4], [5, 6]])
print(x[[0, 1, 2], [0, 1, 1]])

[1 4 6]


In [207]:
import numpy as np

x = np.arange(12).reshape(3,4)
print(x[:,1])

[1 5 9]


In [208]:
import numpy as np

z = np.eye(2)
print(z)

[[1. 0.]
 [0. 1.]]


In [209]:
import numpy as np

x = np.arange(20).reshape(4,5)
print(x.mean(axis=1))

[ 2.  7. 12. 17.]


In [210]:
import numpy as np

print(np.array(([1, 2], (3,4))).shape)

(2, 2)


In [211]:
import numpy as np

x = np.arange(4)
print(x**2)

[0 1 4 9]


In [213]:
import numpy as np

x = np.arange(4)
x

array([0, 1, 2, 3])

In [214]:
print(x.flatten())

[0 1 2 3]


In [215]:
import numpy as np

x = np.array([[0, 1], [1, 1], [2, 2]])
print(x.sum(-1))

[1 2 4]


In [216]:
import numpy as np

x = np.array([[-2], 
              [2]])
y = np.array([[-3, 3]])
print(x.dot(y))

[[ 6 -6]
 [-6  6]]


In [217]:
import numpy as np

y = np.array([3+4j, 0.4+7.8j])
print(y.dtype)

complex128


In [218]:
import numpy as np

x = np.array([[-2], 
              [2]])
y = np.array([[-3, 3]])
print(x + y)

[[-5  1]
 [-1  5]]


In [219]:
import numpy as np

x = np.arange(30).reshape(5,6)
print(x.argmax(axis=1))

[5 5 5 5 5]


In [220]:
import numpy as np

x = np.array([[1, 2], [3, 4], [5, 6]])
print(x[[0, 1, 2], [0, 1, 1]])

[1 4 6]


In [221]:
import numpy as np

x = np.array([[0, 1], [1, 1], [2, 2]])
y = x.sum(-1)
print(x[y < 2, :])

[[0 1]]
